# Server version: 4.0.13
# PHP Version: 4.3.3
# 
USE eseData;

#
# Test data for table `element`
#

INSERT INTO `element` VALUES (0, 0, 0, '', '', '<b>Esekey Limited</b> is a specialist provider of dynamic web-based services for holiday property owners and agents in the UK. The services cover the key areas of web-based holiday property marketing, built on a flexible web site structure that supports viewing of accommodation details, availability and online booking; and browser-based administration of site content and bookings. We are constantly on the look-out for improvements and new features, such as property and inventory management services.  <br><br>At <b>Esekey</b>, we aim to provide everything you&#039;ll need to manage your properties and your bookings and to help you make the most of your presence in the rapidly-growing web marketplace.<br><br>All you need to use the service is a reliable internet connection, a PC with web browser and (optionally) a printer. <br><br>Take a look at our reference site, <a href="http://www.troppo.uk.com/" target="z"><b>Dorney Self Catering Apartments</b></a> and see the benefits for yourself.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', 'As a special introductory offer, <b>Esekey Limited</b> is currently offering free trials to interested holiday property owners and agents in the UK. If you would like to try out our services with no obligation, or would like more information on this offer, ', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', 'click here', 'mailto:offers@esekey.com', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', ' to send us your contact details now, or call us on <b>07860 832741</b>. <br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', '<b>Esekey Limited</b> was founded in 2003 by Dave Lockwood, after many hours of frustration as a customer trying to book self-catering accommodation on the net. With over twenty years of experience in the IT industry, many of them working on high volume transactional systems and e-commerce websites, Dave decided he could do better himself, so he set out to build an online booking system from scratch. His objectives were simple: make it easy to manage, easy to use and low-cost, to appeal directly to individual holiday cottage owners. <br><br>The result is a service that is scaleable from an individual one-bedroom property through to an agency with hundreds of properties.<br><br>All you need to use the service is a reliable internet connection, a PC with web browser and a printer. <br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', '<b>Esekey Limited</b> can provide a range of services for holiday cottage owners and agents in the UK.<br><br> Our services include competitively priced business and technical consultancy and advice on e-commerce and web sites, and we specialise in the creation and hosting of a complete website to order, with availability and online booking built-in, based on our <b>EseSite and EseBooking services</b>.<br><br>For further information,', '', 'Y', now(), 'root', null);
INSERT INTO `element` VALUES (0, 0, 0, '', '', 'click here', 'mailto:info@esekey.com', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', ' to email any questions you may have to us, or call us on <b>07860 832741</b>. <br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', '<b>EseSite</b> is a hosted web application designed to be administered and maintained via the web by the property owner or agent. <br><br>If you do not have a website, or you are looking to replace your current website, EseSite provides the complete solution. It can be set up to use any distinctive style of your choice and you can manage the content yourself through an easy-to-use administration console from your web browser. <br><br>If you have your own website and want to keep it, you can still use <b>EseSite</b> by hyperlinking to it from your own site for availability and other online services. ', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', '<ul><li>Links to/from existing web site or full replacement</li><li>Comprehensive property descriptions with images</li><li>Eye catching list of key property features</li><li>View availability and prices by property</li><li>Availability based on booking pattern specified for property (e.g. Friday - Friday, Saturday-Saturday, off-season short breaks, etc.)</li><li>Immediate booking online with credit/debit card</li><li>Provisional reservation online for 24 hours with personal details but no credit/debit card</li><li>Extra features for group bookings, including property combinations at special rates (optional)</li><li>Cancellation of booking within 24 hours  at no cost (optional)</li><li>Select cancellation insurance, other optional extras (e.g. cot), make additional comments with booking (optional)</li><li>Immediate email confirmation of booking - to both customer and administrator (reserved internal dedicated booking email address - easy to view daily bookings)</li><li>View visitors books (optional)</li></ul>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, 'email.gif', 'left', 'Email us at info@esekey.com', 'mailto:info@esekey.com', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, 'phone.gif', 'left', 'Call us on <b>07860 832741.</b>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (0, 0, 0, '', '', 'This login page is for use only by <br><br>(1) registered users of the EseSite service and <br>(2) interested parties who have contacted us and obtained a temporary user name in order to see a demonstration version of the service. <br><br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, 'beach_panorama2.jpg', 'top', '<b>Fictional Farm</b> is the place to take the whole family for a relaxing break away from the stresses and strains of work, housekeeping and school. <br><br>At <b>Fictional Farm</b>, we pride ourselves in having everything you&#039;ll need to have a great holiday.<br><br>In a beautiful setting, with all our facilities on-site and the beach little more than a stone&#039;s throw away, <b>Fictional Farm Holiday Cottages</b> offer luxurious and relaxing surroundings in five-star comfort for the discerning holidaymaker.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, 'pool.jpg', 'top', '<b>Fictional Farm</b> is the place to take the whole family for a relaxing break away from the stresses and strains of work, housekeeping and school. <br><br>At <b>Fictional Farm</b>, we pride ourselves in having everything you&#039;ll need to have a great holiday.<br><br>In a beautiful setting, with all our facilities on-site and the beach little more than a stone&#039;s throw away, <b>Fictional Farm Holiday Cottages</b> offer luxurious and relaxing surroundings in five-star comfort for the discerning holidaymaker.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (2, 0, 0, 'panorama.jpg', 'top', '<b>National Lodges</b> are the holiday homes to take the whole family for a relaxing break away from the stresses and strains of work, housekeeping and school. <br><br>At <b>National Lodges</b>, we pride ourselves in having everything you&#039;ll need to have a great holiday.<br><br>In a beautiful setting, with all our facilities on-site and the beautiful rolling countryside all around you, <b>National Holiday Lodges</b> offer luxurious and relaxing surroundings in five-star comfort for the discerning holidaymaker.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, 'farmhouse1.jpg', 'top', '<b>Fictional Farm</b> is the place to take the whole family for a relaxing break away from the stresses and strains of work, housekeeping and school. <br><br>At <b>Fictional Farm</b>, we pride ourselves in having everything you&#039;ll need to have a great holiday.<br><br> In a beautiful setting, with all our facilities on-site and the beach little more than a stone&#039;s throw away, <b>Fictional Farm Holiday Cottages</b> offer luxurious and relaxing surroundings in five-star comfort for the discerning holidaymaker.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (2, 0, 0, 'farmhouse1.jpg', 'top', '<b>National Lodges</b> are the holiday homes to take the whole family for a relaxing break away from the stresses and strains of work, housekeeping and school. <br><br>At <b>National Lodges</b>, we pride ourselves in having everything you&#039;ll need to have a great holiday.<br><br>In a beautiful setting, with all our facilities on-site and the beautiful rolling countryside all around you, <b>National Holiday Lodges</b> offer luxurious and relaxing surroundings in five-star comfort for the discerning holidaymaker.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 1, 'barn.jpg', 'top', '<b>Barn Cottage</b> is the second largest cottage on the farm and is capable of sleeping 8, having two double bedrooms, a twin and a single bedroom as well as a sofabed in the lounge.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 2, 'cowshed.jpg', 'top', '<b>Cowshed Cottage</b> is the most modern building on the farm, having been built to extend the farm only thirty years ago. The cottage sleeps 6, having two double bedrooms (both ensuite) and two single bedrooms, making it ideal for a family break with the grandparents and children.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 3, 'farmhouse1.jpg', 'top', '<b>Farmhouse Cottage</b> is the largest cottage, being the main farm building, and is capable of sleeping 10, having two double bedrooms, two twins and two single bedrooms.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 4, 'stable.jpg', 'top', '<b>Stable Cottage</b> is the smallest cottage on the farm and is capable of sleeping 4, having a double bedroom and two single bedrooms.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (2, 0, 1, 'barn.jpg', 'top', '<b>Barn Lodge</b> is the second largest lodge we have and is capable of sleeping 8, having two double bedrooms, a twin and a single bedroom as well as a sofabed in the lounge.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (2, 0, 2, 'cowshed.jpg', 'top', '<b>Cowshed Lodge</b> is the most modern building on the farm, having been built to extend the farm only thirty years ago. The lodge sleeps 6, having two double bedrooms (both ensuite) and two single bedrooms, making it ideal for a family break with the grandparents and children.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (2, 0, 3, 'farmhouse1.jpg', 'top', '<b>Farmhouse Lodge</b> is the largest lodge, being the main farm building, and is capable of sleeping 10, having two double bedrooms, two twins and two single bedrooms.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (2, 0, 4, 'stable.jpg', 'top', '<b>Stable Lodge</b> is the smallest lodge on the farm and is capable of sleeping 4, having a double bedroom and two single bedrooms.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, 'KC_livingroom.jpg', 'top', 'There are three easy ways you can use this site to check availability. <br><br>You can use our ', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, '', '', 'search form', 'availability_search.html', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, '', '', ' to find a cottage matching your search criteria and view its available dates from there; <br>or you can include a start date in your search so that only cottages available on your selected date are shown; or you can look at the ', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, '', '', 'availability summary', 'availability_summary.html', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, '', '', ' and view the available dates and details for an individual cottage from there.<br><br>If you have any suggestions on how to improve this site, we would love to hear from you. ', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, '', '', 'Send us an email', 'mailto:info@esekey.com', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, '', '', ' or call us on 07860 832741.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (1, 0, 0, '', 'top', 'Making a booking for a holiday at <b>Fictional Farm</b> couldn&#039;t be easier.<br><br>You can use our secure online booking system to make an immediate reservation, or you can call us on <b>07860 832741</b> to discuss your requirements in more detail with us and make your booking by phone, by email or by post. <br><br>Either way, your selection can be provisionally booked for 24 hours at no cost to you, or taken as an immediate confirmed booking with a 10 percent deposit taken via credit or debit card.<br><br> That&#039;s how easy it is! Take a look at our great <a href="home_facilities.html">facilities</a>, decide which of our delightful <a href="cottages.html">cottages</a> you prefer, then <a href="availability.html">click here to check availability and enter our secure online booking system</a>.<br><br>When you have found what you want, follow the instructions and book online, or give us a call.<BR><BR>For bookings, queries and local information, call us now on <b>07860 832741</b>.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, 'wisteria2.jpg', 'left', '<b>Welcome</b> to <b><a href="index.php?p=7">Wisteria</a>, <a href="index.php?p=8">Gardener&#039;s Bothy</a></b> and <b><a href="index.php?p=9">The Smithy</a></b>, our <b>Dorney Self Catering Apartments</b> providing quality accommodation in a unique location.<br><br>The apartments are set in the grounds of a Tudor house in a rural, peaceful location in the quiet village of Dorney, yet only ten minutes&#039; drive from Windsor.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, '', '', 'Each of our apartments can accommodate singles, couples or a family, and when combined they can be block-booked by groups of up to 16 people (some in sofabeds).<br><br><img src="pet.jpg" alt="Pets welcome" align="absmiddle">&nbsp;Pets are welcome by prior arrangement.<br><br>We attract regular visits from families (<a href="http://www.legoland.co.uk/" target="x"><b>Legoland</b></a> is a 15 minute drive away) and film crews (<a href="http://www.dorneycourt.co.uk/" target="x"><b>Dorney Court</b></a> is a five minute drive). <br><br>The historic centres of <a href="http://www.eton.co.uk/" target="x"><b>Eton</b></a> and <a href="http://www.windsor.gov.uk/" target="x"><b>Windsor</b></a>, divided by the Thames, can be easily reached, either by a pleasant stroll along the <a href="http://www.nationaltrails.gov.uk/thamespathframeset.htm" target="x"><b>Thames Path</b></a> or by car in about ten minutes.<br><br>There is a large Sainsbury Superstore within 10 minutes&#039; drive.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, 'guestslawn1.jpg', 'left', '<ul><li>All <b>linen, towels, tea towels, heating and electricity</b> are included in the booking price</li><li>There is plenty of <b>secure parking</b> close to the apartments, within the grounds</li><li>There is a <b>large lawn</b> for guests&#039; use</li><li>The <b>washing machine</b> and <b>tumble dryer</b> in the lobby of Gardener&#039;s Bothy can be used by prior arrangement</li><li>A <b>barbecue</b> is available, plus <b>table and chairs</b></li><li><b>Travel cot</b> and <b>extra linen</b> are available on request</li></ul>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, '', '', '<br><p align=center>This motorway map illustrates our M4 corridor&#047;Thames Valley location.<br>We are only 10 minutes&#039; drive from Junction 7 of the M4.<br><br><table background="wherewearebg.jpg" width=383 height=291 border="0" cellspacing="0" cellpadding="0"><tr><td class="map" colspan="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="maprd">M40</span></td></tr><tr><td class="map" colspan="2" align="right"><span class="maprd">M1</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr><tr><td class="map" colspan="2">&nbsp;</td></tr><tr><td class="map" width=190>&nbsp;</td><td class="map" valign="top">&#149;&nbsp;Bekonscot</td></tr><tr><td class="map">&nbsp;</td><td class="map" align="right" valign="bottom"><br>GREATER<br>LONDON</td></tr><tr><td class="map"></td><td class="map" valign="bottom"></td></tr><tr><td class="map" align="right" valign="top">Dorney Lake&nbsp;&#149;&nbsp;&nbsp;<br>&nbsp;</td><td class="map" valign="top">&#149;&nbsp;Eton &amp; Windsor<br>&#149;&nbsp;&nbsp;Legoland<br></td></tr><tr><td class="map"><span class="maprd">M4</span></td><td class="map">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="maprd">M25</span></td></tr><tr><td class="map" align="right">Ascot&nbsp;&#149;</td><td class="map" align="right">&#149;&nbsp;Thorpe Park&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr><tr><td></td><td class="map">&nbsp;</td></tr><tr><td class="map" align="right"><span class="maprd">M3</span></td><td>&nbsp;</td></tr><tr><td class="map" colspan="2">&nbsp;</td></tr></table>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, '', '', 'We are conveniently situated for the following attractions and many more in the South East - please click on the links for more information:-<ul><li><a href="http://www.royal-windsor.com/" target="x"><b>Windsor and Windsor Castle</b></a> also <a href="http://www.windsor.gov.uk/" target="x"><b>Royal Borough</b> - Information 01753 743900</a></li><li><a href="http://www.etoncollege.com/" target="x"><b>Eton College</b> - 01753 671177</a></li><li><a href="http://www.dorneylake.com/" target="x"><b>Dorney Lake</b> - 01753 832756</a></li><li><a href="http://www.legoland.co.uk/" target="x"><b>Legoland</b> - Information and Booking Hotline 08705 040404</a></li><li><a href="http://www.thorpepark.co.uk/" target="x"><b>Thorpe Park</b> - Information 0870 444 4466</a></li><li><a href="http://www.chessington.co.uk/" target="x"><b>Chessington World of Adventures</b> - Information 0870 444 7777</a></li><li><a href="http://www.bekonscot.com/" target="x"><b>Bekonscot Model Village</b> - Beaconsfield - 01494 672919</a></li><li><a href="http://www.thamesweb.co.uk/windsor/greatpark/index.html" target="x"><b>Windsor Great Park and The Savill Garden</b> - Information 01753 847518</a></li><li><a href="http://www.ascot.co.uk/" target="x"><b>Ascot Racecourse</b> - 01344 876876</a></li><li><a href="http://www.windsor-racecourse.co.uk/" target="x"><b>Windsor Racecourse</b> - 0870 220 0024</a></li><li><a href="http://www.boat-trips.co.uk/" target="x"><b>French Brothers Thames Boat Trips</b> - 01753 851900</a></li><li><a href="http://www.theatreroyalwindsor.co.uk/" target="x"><b>Theatre Royal, Windsor</b> - Bookings 01753 853888</a></li><li><a href="http://www.nationaltrust.org.uk/scripts/nthandbook.dll?ACTION=PROPERTY&PropertyId=259" target="x"><b>Cliveden</b> - home of the Astors - 01628 605069</a></li><li><a href="http://www.dorneycourt.co.uk/" target="x"><b>Dorney Court</b> - stately home - 01628 604638</a></li><li><a href="http://www.rbwm.gov.uk/wlc/wlc_pools.htm" target="x"><b>Windsor Leisure Pool</b> - for swimming - 01753 850004</a></li><li><a href="http://www.nationaltrails.gov.uk/thamespathframeset.htm" target="x"><b>Thames Path</b> - 01865 810224 </a></li><li><a href="http://www.thepalmerarms.com" target="x"><b>The Palmer Arms</b> - restaurant and bar - 01628 666612 </a></li></ul>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, 'oldplace.jpg', 'top', '<b>Welcome</b> to <b><a href="index.php?p=7">Wisteria</a>, <a href="index.php?p=8">Gardener&#039;s Bothy</a></b> and <b><a href="index.php?p=9">The Smithy</a></b>, our <b>Dorney Self Catering Apartments.</b> <br><br>The apartments are set in the grounds of a Tudor house in a rural, peaceful, secure location in the quiet hamlet of Dorney, yet only ten minutes drive from Windsor.<br><br>All apartments are self catering and we provide a welcome pack of provisions, including tea, coffee, sugar, milk, butter, bread, marmalade, cereals and orange juice.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 1, 'wisteria.jpg', 'top', '<b>Wisteria</b> is a ground floor apartment having one bedroom with twin beds and a living&#047;dining room. <br><br>The apartment has sofa chairs that open out to form single 3ft wide beds and can sleep a maximum of 5. There is a shower over the bath and a fully equipped kitchen comprising hob and oven, dishwasher, microwave, fridge, toaster and kettle and a television and table, chairs and sofa in the living area.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 2, 'gardenersbothy.jpg', 'left', '<b>Gardener&#039;s Bothy</b> is a first floor barn conversion with two bedrooms - the second is very small. <br><br>The main bedroom has a king size bed.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 2, 'gbinterior.jpg', 'right', 'The apartment has an open plan living&#047;dining&#047;kitchen area.<br><br>The kitchen includes a hob and oven, microwave, fridge, toaster and kettle.<br><br>There is plenty of seating and a television in the living area.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 3, 'smithytemp.jpg', 'top', '<b>The Smithy</b> is a ground floor double aspect studio apartment with separate WC and shower room. The kitchenette includes a two-ring hob, microwave, fridge, toaster and kettle. There is a bunk bed with sofa at the bottom that converts into a double width bed.<br><br>The Smithy sleeps a maximum of 3. There is independent heating, a table and chairs and a television.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, '', '', '<br><p><b>Gardener&#039;s Bothy and Wisteria</b><br><br></p><ul><li>GBP 65.00 per night - includes first two guests</li><li>GBP 10.00 for each additional guest</li><li>Under Fives go free</li><li>Minimum booking fee GBP 80.00</li></ul><p><b>The Smithy</b><br><br></p><ul><li>GBP 50.00 per night</li><li>GBP 30.00 per night if booked in conjunction with Gardener&#039;s Bothy or Wisteria</li></ul><p><b>Rowing Groups</b><br><br></p><ul><li>Rowing Group Bookings, for parties of 8 or more bringing their own towels and sleeping bags or suitable bed linen (pillows and pillowcases are provided) are available at a special rate of GBP 15.00 per person per night</li></ul>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, '', '', '<p style="text-align: center"><b>Conditions of Booking</b><br><br>Accommodation at Wisteria, Gardener&#039;s Bothy & The Smithy</p><ol><li>Reservations must be guaranteed with a 30% non-refundable deposit, this will be taken from your credit card after you have provided your details to us securely online.</li><li>Payment in full is required if the booking is made less than 4 weeks before the start date.</li><li>In the event of cancellation or reduction in the booking, cancellation charges will be calculated at 80% of the value of the booking.</li><li>The 70% balance will be refunded provided that 28 days&#039; clear notice by mail, email or fax is given of cancellation of reservations.</li><li>When making your reservation, by completion of this secure online form you authorise that we may take the balance (70%) of the booking from your credit card 4 weeks prior to arrival or take the cancellation fee as above. Please let us know if your prefer to pay the balance by cash or cheque, otherwise the balance will be processed by credit card.</li><li>Please note that the booking is not confirmed until your deposit payment is successfully processed.</li></ol>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, 'morning_sun_on_wisteria_003.jpg', 'top', 'The early morning sun on Wisteria', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, 'windsorcastle.jpg', 'top', 'Windsor Castle', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, 'River at Eton.jpg', 'top', 'River Thames at Eton', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (3, 0, 0, 'bridge over Jubilee River.jpg', 'top', 'Bridge over Jubilee River', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, 'wisteria2.jpg', 'left', '<b>Welcome</b> to <b><a href="index.php?p=7">Wisteria</a>, <a href="index.php?p=8">Gardener&#039;s Bothy</a></b> and <b><a href="index.php?p=9">The Smithy</a></b>, our <b>Dorney Self Catering Apartments</b> providing quality accommodation in a unique location.<br><br>The apartments are set in the grounds of a Tudor house in a rural, peaceful location in the quiet village of Dorney, yet only ten minutes&#039; drive from Windsor.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, '', '', 'Each of our apartments can accommodate singles, couples or a family, and when combined they can be block-booked by groups of up to 16 people (some in sofabeds).<br><br><img src="pet.jpg" alt="Pets welcome" align="absmiddle">&nbsp;Pets are welcome by prior arrangement.<br><br>We attract regular visits from families (<a href="http://www.legoland.co.uk/" target="x"><b>Legoland</b></a> is a 15 minute drive away) and film crews (<a href="http://www.dorneycourt.co.uk/" target="x"><b>Dorney Court</b></a> is a five minute drive). <br><br>The historic centres of <a href="http://www.eton.co.uk/" target="x"><b>Eton</b></a> and <a href="http://www.windsor.gov.uk/" target="x"><b>Windsor</b></a>, divided by the Thames, can be easily reached, either by a pleasant stroll along the <a href="http://www.nationaltrails.gov.uk/thamespathframeset.htm" target="x"><b>Thames Path</b></a> or by car in about ten minutes.<br><br>There is a large Sainsbury Superstore within 10 minutes&#039; drive.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, 'guestslawn1.jpg', 'left', '<ul><li>All <b>linen, towels, tea towels, heating and electricity</b> are included in the booking price</li><li>There is plenty of <b>secure parking</b> close to the apartments, within the grounds</li><li>There is a <b>large lawn</b> for guests&#039; use</li><li>The <b>washing machine</b> and <b>tumble dryer</b> in the lobby of Gardener&#039;s Bothy can be used by prior arrangement</li><li>A <b>barbecue</b> is available, plus <b>table and chairs</b></li><li><b>Travel cot</b> and <b>extra linen</b> are available on request</li></ul>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, '', '', '<br><p align=center>This motorway map illustrates our M4 corridor&#047;Thames Valley location.<br>We are only 10 minutes&#039; drive from Junction 7 of the M4.<br><br><table background="wherewearebg.jpg" width=383 height=291 border="0" cellspacing="0" cellpadding="0"><tr><td class="map" colspan="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="maprd">M40</span></td></tr><tr><td class="map" colspan="2" align="right"><span class="maprd">M1</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr><tr><td class="map" colspan="2">&nbsp;</td></tr><tr><td class="map" width=190>&nbsp;</td><td class="map" valign="top">&#149;&nbsp;Bekonscot</td></tr><tr><td class="map">&nbsp;</td><td class="map" align="right" valign="bottom"><br>GREATER<br>LONDON</td></tr><tr><td class="map"></td><td class="map" valign="bottom"></td></tr><tr><td class="map" align="right" valign="top">Dorney Lake&nbsp;&#149;&nbsp;&nbsp;<br>&nbsp;</td><td class="map" valign="top">&#149;&nbsp;Eton &amp; Windsor<br>&#149;&nbsp;&nbsp;Legoland<br></td></tr><tr><td class="map"><span class="maprd">M4</span></td><td class="map">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="maprd">M25</span></td></tr><tr><td class="map" align="right">Ascot&nbsp;&#149;</td><td class="map" align="right">&#149;&nbsp;Thorpe Park&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr><tr><td></td><td class="map">&nbsp;</td></tr><tr><td class="map" align="right"><span class="maprd">M3</span></td><td>&nbsp;</td></tr><tr><td class="map" colspan="2">&nbsp;</td></tr></table>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, '', '', 'We are conveniently situated for the following attractions and many more in the South East - please click on the links for more information:-<ul><li><a href="http://www.royal-windsor.com/" target="x"><b>Windsor and Windsor Castle</b></a> also <a href="http://www.windsor.gov.uk/" target="x"><b>Royal Borough</b> - Information 01753 743900</a></li><li><a href="http://www.etoncollege.com/" target="x"><b>Eton College</b> - 01753 671177</a></li><li><a href="http://www.dorneylake.com/" target="x"><b>Dorney Lake</b> - 01753 832756</a></li><li><a href="http://www.legoland.co.uk/" target="x"><b>Legoland</b> - Information and Booking Hotline 08705 040404</a></li><li><a href="http://www.thorpepark.co.uk/" target="x"><b>Thorpe Park</b> - Information 0870 444 4466</a></li><li><a href="http://www.chessington.co.uk/" target="x"><b>Chessington World of Adventures</b> - Information 0870 444 7777</a></li><li><a href="http://www.bekonscot.com/" target="x"><b>Bekonscot Model Village</b> - Beaconsfield - 01494 672919</a></li><li><a href="http://www.thamesweb.co.uk/windsor/greatpark/index.html" target="x"><b>Windsor Great Park and The Savill Garden</b> - Information 01753 847518</a></li><li><a href="http://www.ascot.co.uk/" target="x"><b>Ascot Racecourse</b> - 01344 876876</a></li><li><a href="http://www.windsor-racecourse.co.uk/" target="x"><b>Windsor Racecourse</b> - 0870 220 0024</a></li><li><a href="http://www.boat-trips.co.uk/" target="x"><b>French Brothers Thames Boat Trips</b> - 01753 851900</a></li><li><a href="http://www.theatreroyalwindsor.co.uk/" target="x"><b>Theatre Royal, Windsor</b> - Bookings 01753 853888</a></li><li><a href="http://www.nationaltrust.org.uk/scripts/nthandbook.dll?ACTION=PROPERTY&PropertyId=259" target="x"><b>Cliveden</b> - home of the Astors - 01628 605069</a></li><li><a href="http://www.dorneycourt.co.uk/" target="x"><b>Dorney Court</b> - stately home - 01628 604638</a></li><li><a href="http://www.rbwm.gov.uk/wlc/wlc_pools.htm" target="x"><b>Windsor Leisure Pool</b> - for swimming - 01753 850004</a></li><li><a href="http://www.nationaltrails.gov.uk/thamespathframeset.htm" target="x"><b>Thames Path</b> - 01865 810224 </a></li><li><a href="http://www.thepalmerarms.com" target="x"><b>The Palmer Arms</b> - restaurant and bar - 01628 666612 </a></li></ul>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, 'oldplace.jpg', 'top', '<b>Welcome</b> to <b><a href="index.php?p=7">Wisteria</a>, <a href="index.php?p=8">Gardener&#039;s Bothy</a></b> and <b><a href="index.php?p=9">The Smithy</a></b>, our <b>Dorney Self Catering Apartments.</b> <br><br>The apartments are set in the grounds of a Tudor house in a rural, peaceful, secure location in the quiet hamlet of Dorney, yet only ten minutes drive from Windsor.<br><br>All apartments are self catering and we provide a welcome pack of provisions, including tea, coffee, sugar, milk, butter, bread, marmalade, cereals and orange juice.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 1, 'wisteria.jpg', 'top', '<b>Wisteria</b> is a ground floor apartment having one bedroom with twin beds and a living&#047;dining room. <br><br>The apartment has sofa chairs that open out to form single 3ft wide beds and can sleep a maximum of 5. There is a shower over the bath and a fully equipped kitchen comprising hob and oven, dishwasher, microwave, fridge, toaster and kettle and a television and table, chairs and sofa in the living area.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 2, 'gardenersbothy.jpg', 'left', '<b>Gardener&#039;s Bothy</b> is a first floor barn conversion with two bedrooms - the second is very small. <br><br>The main bedroom has a king size bed.<br><br>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 2, 'gbinterior.jpg', 'right', 'The apartment has an open plan living&#047;dining&#047;kitchen area.<br><br>The kitchen includes a hob and oven, microwave, fridge, toaster and kettle.<br><br>There is plenty of seating and a television in the living area.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 3, 'smithytemp.jpg', 'top', '<b>The Smithy</b> is a ground floor double aspect studio apartment with separate WC and shower room. The kitchenette includes a two-ring hob, microwave, fridge, toaster and kettle. There is a bunk bed with sofa at the bottom that converts into a double width bed.<br><br>The Smithy sleeps a maximum of 3. There is independent heating, a table and chairs and a television.', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, '', '', '<br><p><b>Gardener&#039;s Bothy and Wisteria</b><br><br></p><ul><li>GBP 65.00 per night - includes first two guests</li><li>GBP 10.00 for each additional guest</li><li>Under Fives go free</li><li>Minimum booking fee GBP 80.00</li></ul><p><b>The Smithy</b><br><br></p><ul><li>GBP 50.00 per night</li><li>GBP 30.00 per night if booked in conjunction with Gardener&#039;s Bothy or Wisteria</li></ul><p><b>Rowing Groups</b><br><br></p><ul><li>Rowing Group Bookings, for parties of 8 or more bringing their own towels and sleeping bags or suitable bed linen (pillows and pillowcases are provided) are available at a special rate of GBP 15.00 per person per night</li></ul>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, '', '', '<p style="text-align: center"><b>Conditions of Booking</b><br><br>Accommodation at Wisteria, Gardener&#039;s Bothy & The Smithy</p><ol><li>Reservations must be guaranteed with a 30% non-refundable deposit, this will be taken from your credit card after you have provided your details to us securely online.</li><li>Payment in full is required if the booking is made less than 4 weeks before the start date.</li><li>In the event of cancellation or reduction in the booking, cancellation charges will be calculated at 80% of the value of the booking.</li><li>The 70% balance will be refunded provided that 28 days&#039; clear notice by mail, email or fax is given of cancellation of reservations.</li><li>When making your reservation, by completion of this secure online form you authorise that we may take the balance (70%) of the booking from your credit card 4 weeks prior to arrival or take the cancellation fee as above. Please let us know if your prefer to pay the balance by cash or cheque, otherwise the balance will be processed by credit card.</li><li>Please note that the booking is not confirmed until your deposit payment is successfully processed.</li></ol>', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, 'morning_sun_on_wisteria_003.jpg', 'top', 'The early morning sun on Wisteria', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, 'windsorcastle.jpg', 'top', 'Windsor Castle', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, 'River at Eton.jpg', 'top', 'River Thames at Eton', '', 'Y', now(), 'root', null);

INSERT INTO `element` VALUES (4, 0, 0, 'bridge over Jubilee River.jpg', 'top', 'Bridge over Jubilee River', '', 'Y', now(), 'root', null);

